import type { Metadata } from "next";
import styles from "./layout.module.scss";
import "../globals.css";

export const metadata: Metadata = {
    title: "My Snippets",
    description: "Generated by create next app"
};

export default function RootLayout() {
    return (
        <html lang="en">
            <body>
                <div className={styles.wrapper}>
                    <div className={styles.content}></div>
                </div>
            </body>
        </html>
    );
}
