import type { Metadata } from "next";
import styles from "./layout.module.scss";
import "../globals.css";

export const metadata: Metadata = {
    title: "My Snippets",
    description: "Generated by create next app"
};

interface Props {
    nav: React.ReactNode;
    code: React.ReactNode;
}

export default function RootLayout({ nav, code }: Props) {
    return (
        <html lang="en">
            <body>
                <div className={styles.wrapper}>
                    <div className={styles.content}>
                        {nav}
                        {code}
                    </div>
                </div>
            </body>
        </html>
    );
}
